# vim:ft=kitty

## name:     OC-2 Dark
## author:   Port of opencode's oc-2 theme
## license:  MIT
## upstream: https://github.com/anomalyco/opencode/blob/dev/packages/ui/src/theme/themes/oc-2.json
## blurb:    Warm, high-signal dark theme pulled from opencode's default UI

# Basic colors
foreground              #A0A0A0
background              #1C1C1C
selection_foreground    #EDEDED
selection_background    #3d3411

# Cursor
cursor                  #fab283
cursor_text_color       #1C1C1C

# URL / bell
url_color               #93e9f6
bell_border_color       #fcd53a

# Window borders
active_border_color     #fab283
inactive_border_color   #4d4c4a

# Tab bar
active_tab_foreground   #1C1C1C
active_tab_background   #fab283
inactive_tab_foreground #A0A0A0
inactive_tab_background #232323
tab_bar_background      #121212
tab_bar_margin_color    #121212

# Marks
mark1_foreground #1C1C1C
mark1_background #fab283
mark2_foreground #1C1C1C
mark2_background #edb2f1
mark3_foreground #1C1C1C
mark3_background #93e9f6

# The 16 terminal colors

# black
color0 #171717
color8 #505050

# red
color1 #fc533a
color9 #fd765f

# green
color2  #12c905
color10 #34da2c

# yellow
color3  #fcd53a
color11 #fce180

# blue
color4  #8cb0ff
color12 #a6c1fc

# magenta
color5  #edb2f1
color13 #f7bcfb

# cyan
color6  #93e9f6
color14 #a5f2fd

# white
color7  #ededed
color15 #ffffff
